### ISSUE TITLE
Doesn't Build

### ISSUE THREAD

**Issue by poudink** [MartinF99/QLegacyStyle#1]
I can't get this to build on Arch.
```
[poudink@trashtop ~]$ git clone https://github.com/MartinF99/QLegacyStyle.git
Cloning into 'QLegacyStyle'...
remote: Enumerating objects: 63, done.
remote: Total 63 (delta 0), reused 0 (delta 0), pack-reused 63
Receiving objects: 100% (63/63), 61.03 KiB | 422.00 KiB/s, done.
Resolving deltas: 100% (28/28), done.
[poudink@trashtop ~]$ cd QLegacyStyle/
[poudink@trashtop QLegacyStyle]$ cd build/
[poudink@trashtop build]$ cmake ..
-- The C compiler identification is GNU 12.2.1
-- The CXX compiler identification is GNU 12.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/poudink/QLegacyStyle/build
[poudink@trashtop build]$ make
[  9%] Automatic MOC and UIC for target qlegacystyle
[  9%] Built target qlegacystyle_autogen
[ 18%] Building CXX object CMakeFiles/qlegacystyle.dir/qlegacystyle_autogen/mocs_compilation.cpp.o
[ 27%] Building CXX object CMakeFiles/qlegacystyle.dir/src/qlegacystyle.cpp.o
[ 36%] Building CXX object CMakeFiles/qlegacystyle.dir/src/qlegacystyleplugin.cpp.o
[ 45%] Building CXX object CMakeFiles/qlegacystyle.dir/src/drawutil.cpp.o
[ 54%] Linking CXX shared module libqlegacystyle.so
[ 54%] Built target qlegacystyle
[ 63%] Automatic MOC and UIC for target widgetgallery
[ 63%] Built target widgetgallery_autogen
[ 72%] Building CXX object CMakeFiles/widgetgallery.dir/widgetgallery_autogen/mocs_compilation.cpp.o
[ 81%] Building CXX object CMakeFiles/widgetgallery.dir/src/widgetgallery.cpp.o
[ 90%] Building CXX object CMakeFiles/widgetgallery.dir/src/main.cpp.o
[100%] Linking CXX executable widgetgallery
/usr/bin/ld: CMakeFiles/widgetgallery.dir/src/widgetgallery.cpp.o: in function `WidgetGallery::changeStyle(QString const&)':
widgetgallery.cpp:(.text+0xabb): undefined reference to `QLegacyStyle::QLegacyStyle(QLegacyStyle::StyleType)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/widgetgallery.dir/build.make:132: widgetgallery] Error 1
make[1]: *** [CMakeFiles/Makefile2:113: CMakeFiles/widgetgallery.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
[poudink@trashtop build]$ 
```
This builds a libqlegacystyle.so binary which when installed partially works, but it's clearly missing something.
![image](https://user-images.githubusercontent.com/29778535/223281486-4fbe72ed-9d71-455b-8104-871f3e073b9a.png)

**Comment by MartinF99** [comment]
well the text layout I couldn't fix yet, and the thing that fails to build was the widgetgallery (I have fixed it for now).

**Comment by MartinF99** [comment]
so I will close the issue and opened a new one for the layout issues.

**Comment by poudink** [comment]
you say you've fixed the widgetgallery problem, but it's still not building correctly and I'm getting the same error as before. maybe you forgot to commit the fix? the only thing that seems to have changed is the readme.

**Comment by MartinF99** [comment]
I forgot to push the commit, now it should build. It will still look wrong though, (the texts will still be misaligned and accelerators will still be displayed with &Text

**Comment by MartinF99** [comment]
This also affects the way menus are aligned
